CRUD_App/urls.py
from django.contrib import admin
from django.urls import path
from myapp import views
urlpatterns = [
    path('admin/', admin.site.urls),

    path('AllData/',views.AllData.as_view(),name='AllData'),
    path('AddData/',views.AddData.as_view(),name='AddData'),
    path('UpdateData/<pk>',views.UpdateData.as_view(),name='UpdateData'),
    path('DeleteData/<pk>',views.DeleteData.as_view(),name='DeleteData'),
    
    #SECURITY URLS
    path('SignUp/',views.SignUpUser.as_view(),name='signup'),
    path('SignIn/',views.SignInUser.as_view(),name='signin'),
    path('PasswordChange/',views.PasswordChangeUser.as_view(),name='passchange'),
    path('PassChangeDone/',views.PassChangeDoneUser.as_view()),
    path('SignOut/',views.SignOutUser.as_view(),name='logout'),
    
]

myapp/models.py
from django.db import models

class Student(models.Model):
    Name=models.CharField(max_length=50)
    Course=models.CharField(max_length=50)
    City=models.CharField(max_length=50)

    def __str__(self):
        return self.Name

myapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,PasswordChangeForm
from .models import Student

class StudentForm(forms.ModelForm):
    class Meta:
        model=Student
        fields=['Name','Course','City']

        widgets={
            'Name':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Student Name'}),
            'Course':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Course Name'}),
            'City':forms.TextInput(attrs={'class':'form-control','placeholder':'Enter City Name'}),
        }



"""SECURITY SECTION"""
#Create New User (Register) form of the user
class NewUserForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','email']

        widgets={
            'username':forms.TextInput(attrs={'class':'form-control','placeholder':'Username'}),

            'email':forms.TextInput(attrs={'class':'form-control','placeholder':'Email'}),
        }

    password1=forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'New Password'}),label='Create Password')

    password2=forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Retype Password'}),label='Retype Password')

#Authenticate(Login) form of the user
class LoginUserForm(AuthenticationForm):
    username=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Enter Your Username','autofocus': True}),)

    password=forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Enter The Password','autofocus': True}))

#password change form of the user
class PassChangeForm(PasswordChangeForm):
    old_password=forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Enter Old Password'}))

    new_password1=forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Enter New Password'}),label='New Password')

    new_password2=forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'RE-Enter New Password'}),label='Confirm Password')

myapp/views.py
from .forms import *
from django.shortcuts import render
from django.urls import reverse
from .models import Student
from django.contrib.auth import views as Auth
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import CreateView,TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView,UpdateView,DeleteView


class AllData(LoginRequiredMixin,ListView): 
    model=Student
    template_name='web/content/AllData.html'
    context_object_name='form'
    paginate_by=7

class AddData(SuccessMessageMixin,LoginRequiredMixin,CreateView):
    form_class=StudentForm
    template_name='web/content/AddData.html'
    context_object_name='form'
    success_url='/AddData/'
    success_message='Student Added Successfully!!!'


class UpdateData(SuccessMessageMixin,LoginRequiredMixin,UpdateView):
    model = Student
    form_class=StudentForm
    template_name='web/content/UpdateData.html'
    context_object_name='form'
    success_message='Student Update Successfully!!!'

    def get_success_url(self):
           pk = self.kwargs["pk"]
           return reverse("UpdateData", kwargs={"pk": pk})

class DeleteData(SuccessMessageMixin,LoginRequiredMixin,DeleteView):
    model=Student
    template_name='web/content/DeleteData.html'
    success_url='/AllData/'
    context_object_name='form'
    success_message='Deleted Successfully'


class SignUpUser(SuccessMessageMixin,CreateView):
    form_class=NewUserForm
    template_name='web/security/AddNewUser.html'
    success_url='/SignUp/'
    success_message='Your account has been created!!! Now you can login.'
    

class SignInUser(SuccessMessageMixin,Auth.LoginView):
    authentication_form=LoginUserForm
    template_name='web/security/LoginUser.html'
    success_url='/SignIn/'
    success_message='Welcome to CRUD Application'

class PasswordChangeUser(LoginRequiredMixin,SuccessMessageMixin,Auth.PasswordChangeView):
    form_class=PassChangeForm
    template_name='web/security/PassChangeUser.html'
    success_url='/PassChangeDone/'
    success_message='Your Password Changed Successfully!!!'
    login_url='/SignIn/' 

class PassChangeDoneUser(Auth.PasswordChangeDoneView):
    template_name='web/security/PassChangeUser.html'

class SignOutUser(Auth.LogoutView):
    template_name='web/security/LoginUser.html'

myapp/templates/web/Base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href={% static 'css/bootstrap.css' %}>
</head>
{% block body %}
    <body>
    {% block container %}
        <div class="container-fluid">
            <div class="row">
                
            </div>
        </div>
    {% endblock container %}
</body>
{% endblock body %}
</html>

myapp/templates/web/content/AddData.html
{% extends "web/Base.html" %}

{% block body %}
    
    <body class="bg-danger">
        
{% block container %}
    
    <div class="col-sm-10 offset-1 text-center mt-1">
        <h2 class="alert-dark">Add New Student</h2>
    </div>

    <div class="col-sm-6 offset-3 bg-warning p-2 rounded">
        <form method="post">
            {% csrf_token %}
            {% for fm in form %}
                <strong class="text-dark">{{fm.label_tag}}</strong> {{fm}} <b class="text-danger offset-8">{{fm.errors | striptags}}</b> <br>
            {% endfor %}
            <input type="submit" value='submit' class="btn btn-success offset-5">
        </form>
    </div>
    <a href={% url 'AllData' %} class="btn bg-info offset-3 mt-2">View Students</a><br>

    <div class="col-sm-6 offset-3 mt-2">
        {% if messages %}
            {% for message in messages %}
        <div class="alert alert-success" role="alert">
        <strong>{{message}}</strong>
        </div>
            {% endfor %}
    {% endif %}
    </div>

{% endblock container %}

    </body>

{% endblock body %}

myapp/templates/web/content/AllData.html
{% extends "web/Base.html" %}


{% block body %}

<body class="bg-danger">

    
{% block container %}
    <div class="col-sm-12 text-center mt-1">
        {% if messages %}
            {% for message in messages %}
        <div class="alert alert-success" role="alert">
        <strong>{{message}}</strong>
        </div>
            {% endfor %}
        {% endif %}
    </div>

    <h2 class="text-center alert-warning mt-1">CRUD APPLICATION AWS</h2>
    <h3 class="text-center alert-danger mt-2">I Integrated it via Github Actions</h3>
        <div class="col-sm-11">
            <h3 class="text-center alert-primary offset-1">ALL STUDENTS LIST</h3>
        </div>   

        <div class="col-sm-8 offset-2 bg-primary fw-bold ">

            {% if form %}
                <table class="table table-bordered text-light">
                      <thead class="text-light bg-dark">
                        <tr>
                            <th>Name</th>
                            <th>Course</th>
                            <th>City</th>
                            {% if perms.myapp.change_student and perms.myapp.delete_student %}
                            <th>Edit</th>
                            {% endif %}
                        </tr>
                      </thead>
                      <tbody>
                        {% for fm in form %}
                        <tr>
                            <td>{{fm.Name}}</td>
                            <td>{{fm.Course}}</td>
                            <td>{{fm.City}}</td>
                            
                                {% if perms.myapp.change_student and perms.myapp.delete_student %}
                                  <td> <a href={% url 'UpdateData' fm.id %} class="btn btn-warning btn-sm">update</a>
                                        <a href={% url 'DeleteData' fm.id %} class="btn btn-danger btn-sm">delete</a>
                              </td> 
                                {% endif %}
            
                        </tr>
                        {% endfor %}
                      </tbody>
                </table>
            {% endif %}
        </div>

        <div class="col-sm-8 offset-2 ">
            
            <div class="row align-items-start">
                    <div class="col">

                     {% if perms.myapp.add_student %}
                         <a href={% url 'AddData' %} class="btn btn-light offset-2 ms-1 btn-sm">Add New Student</a> <br>
                     {% endif %}
                     <a href={% url 'logout' %} class="btn btn-dark offset-2 mt-2 ms-1 btn-sm">Sign Out</a>
                    </div>
                    
                    <div class="col">
                      {% if is_paginated %}
            
                        <ul class="pagination offset-9">

                          {% if page_obj.has_previous %}
                          <li class="page-item ">
                            <a class="page-link" href="?page={{page_obj.previous_page_number}}" tabindex="-1" aria-disabled="true">Previous</a>
                          </li>
                          {% endif %}

                          <li class="page-item active" aria-current="page">
                            <a class="page-link" href="#">{{page_obj.number}}</a>
                          </li>
                          
                          {% if page_obj.has_next %}
                          <li class="page-item">
                            <a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a>
                          </li>
                          {% endif %}

                         </ul>
                             
                         {% endif %}
                    </div>
            </div>
        </div>
     
             


{% endblock container %}



</body>

{% endblock  %}

myapp/templates/web/content/DeleteData.html
{% extends "web/Base.html" %}

{% block body %}
    
    <body class="bg-danger">
        
{% block container %}
    
    <div class="col-sm-10 offset-1 text-center mt-1">
        <h2 class="alert-dark">Delete Student</h2>
    </div>

    <div class="col-sm-6 offset-3 bg-warning pt-2 rounded mt-5">


            <form method="post">
                {% csrf_token %}
                <h3 class="text-center font-monospace fw-bolder text-decoration-underline">Are you sure to delete {{object}} ?</h3>
                <input type="submit" value="Yes Delete" class="btn btn-success offset-5">
            </form><br>
        
    </div>
    
      <a href={% url 'AllData' %} class="btn btn-info offset-3 mt-2 ">cancel</a><br>
{% endblock container %}

    </body>

{% endblock body %}

myapp/templates/web/content/UpdateData.html
{% extends "web/Base.html" %}

{% block body %}
    
    <body class="bg-danger">
        
{% block container %}
    
    <div class="col-sm-10 offset-1 text-center mt-1">
        <h2 class="alert-dark">Update Student Data</h2>
    </div>

    <div class="col-sm-4 offset-4 bg-warning p-2 rounded">
        <form method="post">
            {% csrf_token %}
            {% for fm in form %}
                <strong class="text-dark">{{fm.label_tag}}</strong> {{fm}} <b class="text-danger offset-8">{{fm.errors | striptags}}</b> <br>
            {% endfor %}
            <input type="submit" value='Update' class="btn btn-success offset-5">
        </form>
    </div>
    <a href={% url 'AllData' %} class="btn bg-info offset-4 mt-2">Go Back</a>

    <div class="col-sm-4 offset-4 mt-2">
        {% if messages %}
            {% for message in messages %}
        <div class="alert alert-success text-center" role="alert">
        <strong>{{message}}</strong>
        </div>
            {% endfor %}
    {% endif %}
    </div>

{% endblock container %}

    </body>

{% endblock body %}

myapp/templates/web/security/AddNewUser.html
{% extends "web/Base.html" %}

{% block body %}
    <body class="bg-warning">


{% block container %}

    <div class="col-sm-6">
        <h2 class="alert-primary offset-2 text-center mt-5 rounded-3">Sign Up</h2>
        <div class="alert-success offset-2 p-3 rounded-3">
            <form method='post' novalidate>
            {% csrf_token %}
            {% for fm in form %}
                <strong class="text-dark">{{fm.label_tag}}</strong> {{fm}} <b class="text-danger offset-8">{{fm.errors | striptags}}</b> <br>
            {% endfor %}
        <input type="submit" value='submit' class="btn btn-success offset-5">
        </form>
        </div>
        <a href={% url 'signin' %} class="btn bg-info mt-2 offset-2">Login</a>
    </div>
    
    <div class="col-sm-4 offset-4 mt-2">
        {% if messages %}
            {% for message in messages %}
        <div class="alert alert-success text-center" role="alert">
        <strong>{{message}}</strong>
        </div>
            {% endfor %}
    {% endif %}
    </div>    

{% endblock container %}


</body>
{% endblock body %}

myapp/templates/web/security/LoginUser.html
{% extends "web/Base.html" %}

{% block body %}
    <body class="bg-primary">


{% block container %}

    <div class="col-sm-5 offset-3">
        <h2 class="alert-primary offset-2 text-center mt-5 rounded-3">Sign In</h2>
        <div class="alert-success offset-2 p-3 rounded-3">
            <form method="post" novalidate>
                {% csrf_token %}
                 {% for fm in form %}
                <strong class="text-dark">{{fm.label_tag}}</strong> {{fm}} <b class="text-danger offset-6">{{fm.errors | striptags}}</b> <br>
                {% endfor %}
                <input type="submit" value='Login' class="btn btn-outline-success mt-1 offset-5"><br>
            </form>
        </div>
        <a href={% url 'signup' %} class="btn bg-warning mt-1 offset-2">Sign Up</a>

        {% if form.non_field_errors %}
            <div class="alert alert-danger mt-2 offset-2" role="alert">
                    <strong>Login Failed!!!</strong> Wrong Username and Password
            </div>
        {% endif %}

    </div>
    

{% endblock container %}


</body>
{% endblock body %}

myapp/templates/web/security/PassChangeUser.html
{% extends "web/Base.html" %}

{% block body %}
    <body class="bg-info">


{% block container %}

    <div class="col-sm-4 offset-3">
        <h2 class="alert-primary offset-2 text-center mt-5 rounded-3">Change Your Password</h2>
        <div class="alert-dark offset-2 p-3 rounded-3">
            <form method="post" novalidate>
                {% csrf_token %}
                 {% for fm in form %}
                <strong class="text-dark">{{fm.label_tag}}</strong> {{fm}} <b class="text-danger offset-6">{{fm.errors | striptags}}</b> <br>
                {% endfor %}
                <input type="submit" value='Change' class="btn btn-outline-success mt-1 offset-4"><br>
            </form>
        </div>
        <a href={% url 'AllData' %} class="btn bg-warning mt-1 offset-2">AllData</a>

        
    </div>
    

{% endblock container %}


</body>
{% endblock body %} 